# Area Plugin PlConnectChatAttachmentItem / ChatAttachmentItem

default: &default
  pl_connect_chat_attachment_items:
    key: 
test:
  <<: *default
development:
  <<: *default
production:
  <<: *default

