# frozen_string_literal: true

# PlConnectApiController
#
# JSON backend of the Connect chat. Everything the chat UI does at runtime goes
# through this controller.
#
# == Why a dedicated controller instead of the generated ones
# The six PlConnect*ItemControllers are PageItem driven and are regenerated by
# the plugin tooling; any custom action added there would be lost on the next
# run. They also serve the classic CRUD/list/tree screens, which have a
# completely different access model (administrative, role based) from the chat
# itself (per conversation membership).
#
# == Authorization model
# Two independent layers, and both must hold:
#
#   1. Authentication — there has to be a logged in user. Enforced by
#      ApplicationController#authorize plus an explicit check in every action,
#      because an action must never silently fall through to "nil user".
#
#   2. Membership — every single action resolves the conversation through
#      PlConnect::ConversationResolver, which only ever returns conversations
#      the caller is an active member of. A uuid the caller has no membership
#      for is reported as "not found", never as "forbidden", so the endpoint
#      cannot be used to probe which conversations exist.
#
# There is deliberately no controller level *role* requirement. Chatting is not
# an administrative capability — every authenticated user may talk to the
# colleagues they are in a conversation with, and the conversation membership
# is the actual permission. The "may this user use Connect at all" gate belongs
# on the workspace controller, which is the single entry point to the UI.
#
# == CSRF
# ApplicationController downgrades to :null_session for JSON requests, which
# means a request with a missing or wrong CSRF token loses its session and is
# then rejected here with 401. The client therefore has to send the
# X-CSRF-Token header — that is intentional and must not be "fixed" by
# skipping forgery protection.
class PlConnectApiController < ApplicationController
  # Chat is interactive: a browser tab can sit idle for a long time and then
  # fire a request. Rendering JSON errors instead of HTML keeps the client able
  # to react (e.g. show "session expired") rather than parsing a login page.
  before_action :_require_user

  # ---------------------------------------------------------------- read ----

  # GET /pl_connect_api/conversations
  # Sidebar payload: all conversations of the caller plus the presence state of
  # the direct chat partners.
  def conversations
    archived = ActiveModel::Type::Boolean.new.cast(params[:archived]) ? true : false
    chats = resolver.list(archived: archived).includes(:pl_connect_chat_item_join_users)

    payload = chats.map do |chat|
      PlConnect::MessageSerializer.conversation_as_json(chat: chat, viewer: current_chat_user)
    end

    render json: {
      successful: true,
      conversations: payload,
      presence: _presence_for(payload.filter_map { |entry| entry[:partner_uuid] }),
      unread_total: read_state.total_unread,
      unread_mentions: read_state.unread_mentions
    }
  rescue StandardError => e
    _render_exception(e, "conversations")
  end

  # GET /pl_connect_api/messages
  # Cursor based history of one conversation. Paging by (sent_at, id) instead of
  # by offset, because offsets shift whenever a new message arrives and would
  # make the client skip or duplicate rows while scrolling up.
  def messages
    chat = resolver.find(params[:chat_uuid])
    return _render_not_found if chat.blank?

    scope = PlConnectChatMessageItem.for_chat(chat.id)
    scope = scope.root_level unless ActiveModel::Type::Boolean.new.cast(params[:include_thread_replies])

    before = _cursor_message(chat)
    scope = scope.older_than(before.sent_at, before.id) if before.present?

    # Fetch newest-first for the cursor, then reverse so the client can append
    # in reading order without sorting again.
    page = scope.reorder(sent_at: :desc, id: :desc).limit(page_size)
                .includes(:sender, :reactions, :attachments).to_a.reverse

    render json: {
      successful: true,
      chat: PlConnect::MessageSerializer.conversation_as_json(chat: chat, viewer: current_chat_user),
      messages: page.map { |m| PlConnect::MessageSerializer.as_json(message: m, viewer: current_chat_user) },
      has_more: page.size == page_size
    }
  rescue StandardError => e
    _render_exception(e, "messages")
  end

  # GET /pl_connect_api/thread
  # Replies of one message, used by the thread side panel.
  def thread
    chat = resolver.find(params[:chat_uuid])
    return _render_not_found if chat.blank?

    root = _find_message(chat, params[:message_uuid])
    return _render_not_found if root.blank?

    replies = PlConnectChatMessageItem.where(parent_id: root.id, del_flag: false)
                                      .order(:sent_at, :id)
                                      .includes(:sender, :reactions, :attachments)

    render json: {
      successful: true,
      root: PlConnect::MessageSerializer.as_json(message: root, viewer: current_chat_user),
      messages: replies.map { |m| PlConnect::MessageSerializer.as_json(message: m, viewer: current_chat_user) }
    }
  rescue StandardError => e
    _render_exception(e, "thread")
  end

  # GET /pl_connect_api/search
  # Full text search over the plain text column, plus a people lookup so the
  # single top bar search field can cover both "search_placeholder" promises
  # (messages and people) instead of only the former.
  #
  # The message scope is restricted to the caller's own conversations *before*
  # the LIKE is applied, so the search can never surface a message from a
  # conversation the caller is not a member of. The people lookup reuses
  # ConversationResolver#searchable_users, i.e. the same tenant-scoped,
  # capped candidate list as the "new chat" user picker - it cannot be used to
  # enumerate the whole user table either.
  def search
    term = params[:term].to_s.strip
    return render json: { successful: true, messages: [], people: [] } if term.length < 2

    render json: {
      successful: true,
      messages: _search_messages(term),
      people: _search_people(term)
    }
  rescue StandardError => e
    _render_exception(e, "search")
  end

  # GET /pl_connect_api/users
  # Candidates for a new chat or for a mention. Tenant scoped and capped, so it
  # cannot be used to enumerate the user table.
  def users
    candidates = resolver.searchable_users(term: params[:term])
    payload = candidates.map { |user| { uuid: user.uuid, login: user.login.to_s, title: user.try(:full_name).to_s } }

    render json: {
      successful: true,
      users: payload,
      presence: _presence_for(payload.map { |entry| entry[:uuid] })
    }
  rescue StandardError => e
    _render_exception(e, "users")
  end

  # GET /pl_connect_api/presence
  def presence
    render json: { successful: true, presence: _presence_for(params[:uuids]) }
  rescue StandardError => e
    _render_exception(e, "presence")
  end

  # --------------------------------------------------------------- write ----

  # POST /pl_connect_api/open_direct
  def open_direct
    result = resolver.open_direct(partner_uuid: params[:partner_uuid])
    return _render_failure(result[:successful_text]) unless result[:successful]

    render json: {
      successful: true,
      chat: PlConnect::MessageSerializer.conversation_as_json(chat: result[:element], viewer: current_chat_user)
    }
  rescue StandardError => e
    _render_exception(e, "open_direct")
  end

  # POST /pl_connect_api/create_group
  def create_group
    result = resolver.create_group(title: params[:title], member_uuids: params[:member_uuids])
    return _render_failure(result[:successful_text]) unless result[:successful]

    render json: {
      successful: true,
      chat: PlConnect::MessageSerializer.conversation_as_json(chat: result[:element], viewer: current_chat_user)
    }
  rescue StandardError => e
    _render_exception(e, "create_group")
  end

  # POST /pl_connect_api/create_message
  def create_message
    chat = resolver.find(params[:chat_uuid])
    return _render_not_found if chat.blank?

    result = composer(chat).create(
      body: params[:body],
      parent_uuid: params[:parent_uuid],
      reply_to_uuid: params[:reply_to_uuid]
    )
    return _render_failure(result[:successful_text]) unless result[:successful]

    render json: {
      successful: true,
      message: PlConnect::MessageSerializer.as_json(message: result[:element], viewer: current_chat_user)
    }
  rescue StandardError => e
    _render_exception(e, "create_message")
  end

  # POST /pl_connect_api/update_message
  def update_message
    chat = resolver.find(params[:chat_uuid])
    return _render_not_found if chat.blank?

    message = _find_message(chat, params[:message_uuid])
    return _render_not_found if message.blank?

    result = composer(chat).update(message: message, body: params[:body])
    return _render_failure(result[:successful_text]) unless result[:successful]

    render json: {
      successful: true,
      message: PlConnect::MessageSerializer.as_json(message: result[:element], viewer: current_chat_user)
    }
  rescue StandardError => e
    _render_exception(e, "update_message")
  end

  # POST /pl_connect_api/delete_message
  def delete_message
    chat = resolver.find(params[:chat_uuid])
    return _render_not_found if chat.blank?

    message = _find_message(chat, params[:message_uuid])
    return _render_not_found if message.blank?

    result = composer(chat).destroy(message: message)
    return _render_failure(result[:successful_text]) unless result[:successful]

    render json: { successful: true, message_uuid: message.uuid }
  rescue StandardError => e
    _render_exception(e, "delete_message")
  end

  # POST /pl_connect_api/toggle_reaction
  def toggle_reaction
    chat = resolver.find(params[:chat_uuid])
    return _render_not_found if chat.blank?

    message = _find_message(chat, params[:message_uuid])
    return _render_not_found if message.blank?

    service = PlConnect::ReactionService.new(c: @c, user: current_chat_user)
    result = service.toggle(chat_item: chat, message: message, emoji: params[:emoji])
    return _render_failure(result[:successful_text]) unless result[:successful]

    render json: {
      successful: true,
      message_uuid: message.uuid,
      reactions: PlConnect::MessageSerializer.reactions_json(message: result[:element], viewer: current_chat_user)
    }
  rescue StandardError => e
    _render_exception(e, "toggle_reaction")
  end

  # POST /pl_connect_api/mark_read
  def mark_read
    chat = resolver.find(params[:chat_uuid])
    return _render_not_found if chat.blank?

    result = read_state.mark_read(chat_item: chat, message_uuid: params[:message_uuid])
    return _render_failure(result[:successful_text]) unless result[:successful]

    render json: {
      successful: true,
      unread_count: result[:element].unread_count.to_i,
      unread_total: read_state.total_unread
    }
  rescue StandardError => e
    _render_exception(e, "mark_read")
  end

  # -------------------------------------------------------------- calls ----

  # POST /pl_connect_api/start_call
  # Starts a call for the conversation, or joins the one already
  # ringing/active in it. For a direct (1:1) conversation this invites the
  # other member and rings; for a group/channel/team conversation it starts a
  # conference immediately and every other member can join in later via the
  # same accept flow as answer_call (see PlConnect::CallService).
  def start_call
    chat = resolver.find(params[:chat_uuid])
    return _render_not_found if chat.blank?

    result = call_service(chat).start
    return _render_failure(result[:successful_text]) unless result[:successful]

    render json: { successful: true, call: _call_json(result[:element]) }
  rescue StandardError => e
    _render_exception(e, "start_call")
  end

  # POST /pl_connect_api/answer_call
  # accept=true|false — for a direct call, the callee's response to an
  # incoming invite; for a conference call, a member joining (accept=true) or
  # dismissing a notification without joining (accept=false, a no-op — see
  # PlConnect::CallService#decline).
  def answer_call
    chat = resolver.find(params[:chat_uuid])
    return _render_not_found if chat.blank?

    call = _find_call(chat, params[:call_uuid])
    return _render_not_found if call.blank?

    accept = ActiveModel::Type::Boolean.new.cast(params[:accept])
    result = accept ? call_service(chat).accept(call: call) : call_service(chat).decline(call: call)
    return _render_failure(result[:successful_text]) unless result[:successful]

    render json: { successful: true, call: _call_json(result[:element].reload) }
  rescue StandardError => e
    _render_exception(e, "answer_call")
  end

  # POST /pl_connect_api/hangup_call
  def hangup_call
    chat = resolver.find(params[:chat_uuid])
    return _render_not_found if chat.blank?

    call = _find_call(chat, params[:call_uuid])
    return _render_not_found if call.blank?

    result = call_service(chat).hangup(call: call)
    return _render_failure(result[:successful_text]) unless result[:successful]

    render json: { successful: true, call: _call_json(result[:element].reload) }
  rescue StandardError => e
    _render_exception(e, "hangup_call")
  end

  # POST /pl_connect_api/call_media_state
  # Persists a mute/camera/screen-share toggle. The realtime broadcast to the
  # other participant happens inside PlConnect::CallService#update_media_state,
  # not in this action.
  def call_media_state
    chat = resolver.find(params[:chat_uuid])
    return _render_not_found if chat.blank?

    call = _find_call(chat, params[:call_uuid])
    return _render_not_found if call.blank?

    result = call_service(chat).update_media_state(
      call: call,
      audio_active: params[:audio_active],
      video_active: params[:video_active],
      screen_active: params[:screen_active]
    )
    return _render_failure(result[:successful_text]) unless result[:successful]

    render json: { successful: true }
  rescue StandardError => e
    _render_exception(e, "call_media_state")
  end

  # ---------------------------------------------------------- attachments ---

  # POST /pl_connect_api/upload_attachment
  def upload_attachment
    chat = resolver.find(params[:chat_uuid])
    return _render_not_found if chat.blank?

    message = _find_message(chat, params[:message_uuid])
    return _render_not_found if message.blank?

    service = PlConnect::AttachmentService.new(c: @c, user: current_chat_user)
    result = service.attach(chat_item: chat, message: message, uploaded_file: params[:file])
    return _render_failure(result[:successful_text]) unless result[:successful]

    render json: {
      successful: true,
      message: PlConnect::MessageSerializer.as_json(message: message.reload, viewer: current_chat_user)
    }
  rescue StandardError => e
    _render_exception(e, "upload_attachment")
  end

  # POST /pl_connect_api/upload_voicemail
  #
  # Delivers a recording made after CallVoicemailTimeoutJob ended an
  # unanswered direct call and prompted the caller (see
  # pl_connect_call_controller.js#startVoicemailRecording). The recording is
  # NOT a call system message: it is created here as a completely ordinary
  # chat message (a fixed, localised caption body) with an audio attachment,
  # so it renders and downloads exactly like any other voice attachment - see
  # message_renderer.js, which never renders attachments for "call_event"/
  # "system" messages.
  def upload_voicemail
    chat = resolver.find(params[:chat_uuid])
    return _render_not_found if chat.blank?

    create_result = composer(chat).create(body: I18n.t("pl_connect.chat.voicemail_caption"))
    return _render_failure(create_result[:successful_text]) unless create_result[:successful]

    message = create_result[:element]
    service = PlConnect::AttachmentService.new(c: @c, user: current_chat_user)
    attach_result = service.attach(chat_item: chat, message: message, uploaded_file: params[:file])
    return _render_failure(attach_result[:successful_text]) unless attach_result[:successful]

    render json: {
      successful: true,
      message: PlConnect::MessageSerializer.as_json(message: message.reload, viewer: current_chat_user)
    }
  rescue StandardError => e
    _render_exception(e, "upload_voicemail")
  end

  # GET /pl_connect_api/download_attachment
  #
  # The only way to get an attachment's bytes. Membership is re-checked here on
  # every single request — a uuid that leaked into a browser history or a chat
  # log stays useless to anyone outside the conversation.
  def download_attachment
    service = PlConnect::AttachmentService.new(c: @c, user: current_chat_user)
    attachment = service.find_for_download(params[:uuid])
    return head :not_found if attachment.blank?

    binary = service.binary_for(attachment)
    return head :not_found if binary.blank?

    # nosniff is what makes the content type allow list in AttachmentService
    # effective: without it a browser may ignore application/octet-stream and
    # sniff the body as HTML, which would execute in this application's origin.
    response.headers["X-Content-Type-Options"] = "nosniff"

    send_data binary,
              filename: attachment.file_name.presence || "attachment",
              type: service.download_content_type(attachment),
              disposition: service.download_disposition(attachment)
  rescue StandardError => e
    Rails.logger.error "PlConnectApiController#download_attachment: #{e.class}: #{e.message}"
    head :internal_server_error
  end

  private

  # --- authorization -------------------------------------------------------

  # Overrides the role based check of PermissionControllerConcern.
  #
  # The default implementation requires a role named after the controller
  # ("plugin_pl_connect_api" / "pl_connect_api"). That is the wrong granularity
  # here: access is decided per conversation, not per controller, and requiring
  # an extra role would mean an administrator has to grant it to literally
  # every user before anyone can chat. Authentication is still mandatory.
  def user_has_permission?
    session[:user].present?
  end

  def _require_user
    return if current_chat_user.present?

    render json: { successful: false, successful_text: I18n.t("alert.message.no_authorization") },
           status: :unauthorized
  end

  def current_chat_user
    @current_chat_user ||= session[:user]
  end

  # --- collaborators -------------------------------------------------------

  def resolver
    @resolver ||= PlConnect::ConversationResolver.new(c: @c, user: current_chat_user)
  end

  def read_state
    @read_state ||= PlConnect::ReadStateService.new(c: @c, user: current_chat_user)
  end

  def composer(chat)
    PlConnect::MessageComposer.new(c: @c, chat_item: chat, user: current_chat_user)
  end

  def call_service(chat)
    PlConnect::CallService.new(c: @c, chat_item: chat, user: current_chat_user)
  end

  # --- helpers -------------------------------------------------------------

  # Always scoped to the conversation, so a message uuid of a foreign
  # conversation cannot be addressed even if the caller knows it.
  def _find_message(chat, uuid)
    return nil if uuid.blank?

    PlConnectChatMessageItem.find_by(uuid: uuid, chat_item_id: chat.id, del_flag: false)
  end

  def _cursor_message(chat)
    _find_message(chat, params[:before_uuid])
  end

  # Message half of the top bar search. Scoped to the caller's own
  # conversations (archived included) before the LIKE is applied.
  def _search_messages(term)
    chat_uuids = resolver.list(archived: true).pluck(:uuid) | resolver.list.pluck(:uuid)
    return [] if chat_uuids.empty?

    # LIKE with a bound, escaped pattern: portable across MySQL, PostgreSQL and
    # SQLite. ILIKE would be PostgreSQL only, REGEXP MySQL only.
    pattern = "%#{term.gsub("\\", "\\\\\\\\").gsub("%", "\\%").gsub("_", "\\_")}%"

    hits = PlConnectChatMessageItem
           .where(chat_item_uuid: chat_uuids, del_flag: false, f_type: "message")
           .where("LOWER(body_plain) LIKE LOWER(:p)", p: pattern)
           .order(sent_at: :desc).limit(50)
           .includes(:sender, :reactions, :attachments)

    hits.map { |m| PlConnect::MessageSerializer.as_json(message: m, viewer: current_chat_user) }
  end

  # People half of the top bar search. Reuses the same tenant-scoped, capped
  # candidate list as the "new chat" user picker (see #users below) so a
  # colleague found here can be opened into a direct chat the same way.
  def _search_people(term)
    resolver.searchable_users(term: term, limit: 8).map do |user|
      { uuid: user.uuid, login: user.login.to_s, title: user.try(:full_name).to_s }
    end
  end

  # Always scoped to the conversation, mirroring _find_message — a call uuid
  # of a foreign conversation cannot be addressed even if the caller knows it.
  def _find_call(chat, uuid)
    return nil if uuid.blank?

    PlConnectCallItem.find_by(uuid: uuid, chat_item_id: chat.id, del_flag: false)
  end

  def _call_json(call)
    {
      uuid: call.uuid,
      room_key: call.room_key,
      f_type: call.f_type,
      state: call.state,
      started_at: call.started_at&.iso8601,
      ended_at: call.ended_at&.iso8601,
      duration_seconds: call.duration_seconds,
      ice_servers: PlConnect::CallService.ice_servers
    }
  end

  def page_size
    configured = PLUGIN&.dig(:pl_connect_chat_item, :message_page_size).to_i
    size = configured.positive? ? configured : 50
    # Hard cap regardless of configuration, so one request cannot pull the
    # whole conversation into memory.
    [ size, 200 ].min
  end

  def _presence_for(uuids)
    return {} unless PlConnect::PresenceService.active?

    PlConnect::PresenceService.states_for(Array(uuids))
  end

  # --- responses -----------------------------------------------------------

  def _render_not_found
    # Same response for "does not exist" and "not yours" on purpose.
    render json: { successful: false, successful_text: I18n.t("alert.message.no_authorization") },
           status: :not_found
  end

  def _render_failure(text)
    render json: { successful: false, successful_text: text.to_s }, status: :unprocessable_entity
  end

  # Logs class and message only. Chat payloads contain personal data and must
  # not end up in the application log (GDPR Art. 5 (1) c).
  def _render_exception(error, context)
    Rails.logger.error "PlConnectApiController##{context}: #{error.class}: #{error.message}"
    render json: { successful: false, successful_text: I18n.t("alert.message.error") },
           status: :internal_server_error
  end
end
