# frozen_string_literal: true

# PlConnectChatMessageItem
#
# A single message inside a conversation.
#
# `f_type` distinguishes three kinds of rows:
#   * "message"    — written by a user, `body` holds sanitised HTML
#   * "system"     — generated by the system (member joined, topic changed, ...);
#                    rendered from `system_event_key` + `system_event_payload`
#                    so it can be translated per viewer
#   * "call_event" — reports a call state change, links to `call_item_uuid`
#
# Threads use the generic `parent_id` column: a reply carries the uuid/id of the
# message that opened the thread. `reply_to_id` is something different — it is a
# flat quote reference inside the same list.
class PlConnectChatMessageItem < ApplicationRecord
  include AssociationOriginalModelConcern

  F_TYPES = %w[message system call_event].freeze

  belongs_to :chat_item, class_name: "PlConnectChatItem", foreign_key: "chat_item_id", optional: true, inverse_of: false
  belongs_to :sender, class_name: "User", foreign_key: "sender_user_id", optional: true, inverse_of: false

  has_many :reactions, -> { where(del_flag: false) },
           class_name: "PlConnectChatReactionItem", foreign_key: "message_id", dependent: :destroy, inverse_of: false

  has_many :attachments, -> { where(del_flag: false).order(:decimal_position, :id) },
           class_name: "PlConnectChatAttachmentItem", foreign_key: "message_id", dependent: :destroy, inverse_of: false

  has_many :mentions, -> { where(del_flag: false) },
           class_name: "PlConnectChatMentionItem", foreign_key: "message_id", dependent: :destroy, inverse_of: false

  validates :f_type, inclusion: { in: F_TYPES }, allow_blank: true

  # Messages of one conversation in display order, newest last.
  def self.for_chat(chat_item_id)
    where(chat_item_id: chat_item_id, del_flag: false).order(:sent_at, :id)
  end

  # Only the top level of the conversation; thread replies are loaded on demand.
  def self.root_level
    where(parent_id: nil)
  end

  # Cursor pagination: everything strictly older than the given message, newest
  # first. The `id` tie-breaker keeps the order stable when two messages share
  # the same `sent_at`.
  def self.older_than(sent_at, id)
    return all if sent_at.blank?

    where("(sent_at < :sent_at) OR (sent_at = :sent_at AND id < :id)", sent_at: sent_at, id: id.to_i)
  end

  # "call_event" rows are system-generated too (see the class doc above) and
  # must be rendered the same way as "system" rows - this used to only check
  # for "system" and silently dropped system_event_data for every call event
  # (see MessageSerializer#as_json), which is why call messages showed the
  # raw, un-interpolated "%{login}" placeholder instead of a real name.
  def system_message?
    %w[system call_event].include?(f_type)
  end

  def edited?
    edited_at.present?
  end

  # Reactions grouped for rendering: { "👍" => [user_uuid, ...] }.
  def reactions_by_emoji
    reactions.group_by(&:emoji).transform_values { |rows| rows.map(&:user_uuid) }
  end

  # Parsed payload of a system message. Returns an empty hash for anything that
  # is not valid JSON so a corrupted row can never break the message list.
  def system_event_data
    return {} if system_event_payload.blank?

    JSON.parse(system_event_payload)
  rescue JSON::ParserError
    {}
  end
end
